name: flutter_kinesis_video_webrtc
description: is a Flutter package that enables seamless integration between AWS Kinesis Video Streams and WebRTC technology within your Flutter applications.
version: 0.0.4
license: MIT
homepage: https://github.com/cloudwebrtc/flutter-webrtc

platforms:
  ios:
  android:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  crypto: ^3.0.3
  aws_client: ^0.4.0
  aws_kinesis_video_signaling_api: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


